routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::get('usuarios', [App\Http\Controllers\UsuariosController::class, 'index'])->name('usuarios');
Route::get('usuarios/crear', [App\Http\Controllers\UsuariosController::class, 'create'])->name('usuarios.crear');
Route::post('usuarios.store', [App\Http\Controllers\UsuariosController::class, 'store'])->name('usuarios.store');*/

Route::resource('usuarios', App\Http\Controllers\UsuariosController::class);

app/Models/Categoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    use HasFactory;

    public function usuarios()
    {
        return $this->belongsTo('App\Models\Usuario','categoria_id');
    }


}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Usuario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Usuario extends Model
{
    use HasFactory;

    protected $fillable = [
        'cedula', 'nombres','apellidos','email','pais','direccion','celular','categoria_id'
    ];

    public function categoria()
    {
        return $this->hasMany('App\Models\Categoria','id','categoria_id');
    }


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/UsuariosController.php
<?php

namespace App\Http\Controllers;

use App\Mail\NotificacionAdmin;
use App\Mail\NotificacionUsuario;
use App\Models\Categoria;
use App\Models\Usuario;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;

class UsuariosController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $usuarios = Usuario::all();
        return view('usuarios')
            ->with('usuarios', $usuarios);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $paises = ($this->flitrarPaises());
        $categorias = Categoria::all();

        return view('usuarios_crear')
        ->with('paises', $paises)
        ->with('categorias', $categorias);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $this->validate($request,[
            'cedula'=>'required|unique:usuarios,cedula',
            'nombres'=>'required|max:100|min:5',
            'apellidos'=>'required|max:100|min:5',
            'email'=>'required|max:150|email',
            'direccion'=>'required|max:180',
            'celular'=>'required|numeric',
        ]);
        //dd($data);
        try {

            DB::beginTransaction();
            $input = [
            'cedula' => $data['cedula'],
            'nombres' => $data['nombres'],
            'apellidos' => $data['apellidos'],
            'email' => $data['email'],
            'pais' => $data['pais'],
            'direccion' => $data['direccion'],
            'celular' => $data['celular'],
            'categoria_id' => $data['categoria'],
            ];
            $usuario = Usuario::create($input);

            Mail::to($usuario->email)->send(new NotificacionUsuario($usuario));
            $this->notificacionAdmin();

            DB::commit();

            return redirect(route('usuarios.index'))
                ->with('success', 'Usuario creado exitosamente.');


        }catch(\Exception $e){
            //dd($e->getMessage());
            return redirect(route('usuarios.index'))
                ->with('error', 'Error creando usuario.'.$e->getMessage());
        }

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $usuario = Usuario::find($id);
        $paises = ($this->flitrarPaises());
        $categorias = Categoria::all();

        return view('usuarios_editar')
        ->with('paises', $paises)
        ->with('categorias', $categorias)
        ->with('usuario', $usuario);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $data = $request->all();
        //dd($data);
        try {

            DB::beginTransaction();

            Usuario::find($id)->update([
                'cedula' => $data['cedula'],
                'nombres' => $data['nombres'],
                'apellidos' => $data['apellidos'],
                'email' => $data['email'],
                'pais' => $data['pais'],
                'direccion' => $data['direccion'],
                'celular' => $data['celular'],
                'categoria_id' => $data['categoria']
            ]);

            DB::commit();

            return redirect(route('usuarios.index'))
                ->with('success', 'Usuario editado exitosamente.');


        }catch(\Exception $e){
            //dd($e->getMessage());
            return redirect(route('usuarios.index'))
                ->with('error', 'Error editando usuario.'.$e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {

        try {

            DB::beginTransaction();

            Usuario::find($id)->delete();

            DB::commit();

            return redirect(route('usuarios.index'))
                ->with('success', 'Usuario borrado exitosamente.');


        }catch(\Exception $e){
            //dd($e->getMessage());
            return redirect(route('usuarios.index'))
                ->with('error', 'Error borradoo usuario.'.$e->getMessage());
        }
    }

    private function getPaises()
    {
        $curl = curl_init();

        curl_setopt_array($curl, array(
          CURLOPT_URL => 'https://restcountries.com/v3.1/region/South%20America',
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_ENCODING => '',
          CURLOPT_MAXREDIRS => 10,
          CURLOPT_TIMEOUT => 0,
          CURLOPT_FOLLOWLOCATION => true,
          CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
          CURLOPT_CUSTOMREQUEST => 'GET',
        ));

        $response = curl_exec($curl);
        curl_close($curl);

        return $response;
    }

    private function flitrarPaises()
    {
        $paises = json_decode($this->getPaises(),true);
        $data = [];
        foreach($paises As $pais)
        {
            $data[$pais['name']['common']] = $pais['name']['common'];
        }
        return $data;
    }

    private function notificacionAdmin()
    {
        $correoAdmin = env('ADMIN_CORREO');
        Mail::to($correoAdmin)->send(new NotificacionAdmin());
    }
}

resources/views/app.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Checkout example · Bootstrap v5.3</title>

<link href="https://getbootstrap.com/docs/5.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

  </head>
  <body class="bg-light">

<div class="container">
  <main>
    <div class="py-5 text-center">
      <h2>@yield('titulo')</h2>
    </div>

    <div class="row g-5">
      <div class="col-md-7 col-lg-12">
        @yield('contenido')
      </div>
    </div>
  </main>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2023 Omar developer</p>
  </footer>
</div>

    <script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/usuarios.blade.php
@extends('app')

@section('titulo','Usuarios')

@section('contenido')

@if ($errors->any())
    <div class="col-sm-12">
        <div class="alert  alert-warning alert-dismissible fade show" role="alert">
            @foreach ($errors->all() as $error)
                <span><p>{{ $error }}</p></span>
            @endforeach
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
    </div>
@endif

@if (session('success'))
    <div class="col-sm-12">
        <div class="alert  alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
    </div>
@endif

@if (session('error'))
    <div class="col-sm-12">
        <div class="alert  alert-danger alert-dismissible fade show" role="alert">
            {{ session('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
    </div>
@endif


<a class="btn btn-primary" href="{{ route('usuarios.create') }}">Crear usuario</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Cedula</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Email</th>
            <th>Celular</th>
            <th>Categoria</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($usuarios as $usuario)
            <tr>
            <td>{!! $usuario->cedula !!}</td>
            <td>{!! $usuario->nombres !!}</td>
            <td>{!! $usuario->apellidos !!}</td>
            <td>{!! $usuario->email !!}</td>
            <td>{!! $usuario->celular !!}</td>
            <td>{!! $usuario->categoria()->first()->categoria !!}</td>
            <td>
                <a class="btn btn-success" href="{!! route('usuarios.edit',[$usuario->id]) !!}">Editar</a>
                <form action="{{ route('usuarios.destroy', $usuario->id) }}" style="display:inline" method="POST" onsubmit="return confirm('¿Está seguro?');">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Borrar">Borrar</button>
                </form>
            </td>
            </tr>
        @endforeach
    </tbody>
</table>

@endsection

resources/views/usuarios_crear.blade.php
@extends('app')

@section('titulo','Usuarios')

@section('contenido')

@if ($errors->any())
    <div class="col-sm-12">
        <div class="alert  alert-warning alert-dismissible fade show" role="alert">
            @foreach ($errors->all() as $error)
                <span><p>{{ $error }}</p></span>
            @endforeach
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
    </div>
@endif

@if (session('success'))
    <div class="col-sm-12">
        <div class="alert  alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
    </div>
@endif

@if (session('error'))
    <div class="col-sm-12">
        <div class="alert  alert-danger alert-dismissible fade show" role="alert">
            {{ session('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
    </div>
@endif

<form method="POST" action="{{ route('usuarios.store') }}">
    {{ csrf_field() }}
    <div class="mb-3">
      <label for="cedula" class="form-label">Cedula</label>
      <input type="number" class="form-control" id="cedula" name="cedula" >
    </div>
    <div class="mb-3">
        <label for="nombres" class="form-label">Nombres</label>
        <input type="text" class="form-control" id="nombres" name="nombres">
    </div>
    <div class="mb-3">
        <label for="apellidos" class="form-label">Apellidos</label>
        <input type="text" class="form-control" id="apellidos" name="apellidos">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email">
    </div>
    <div class="mb-3">
        <label for="pais" class="form-label">Pais</label>
        <select id="pais" name="pais" class="form-select">
            <option>seleccionar</option>
            @foreach ($paises as $key=>$pais)
            <option value="{!! $key !!}">{!! $pais !!}</option>
            @endforeach
        </select>
    </div>
    <div class="mb-3">
        <label for="direccion" class="form-label">Dirección</label>
        <input type="text" class="form-control" id="direccion" name="direccion">
    </div>
    <div class="mb-3">
        <label for="celular" class="form-label">Celular</label>
        <input type="number" class="form-control" id="celular" name="celular">
    </div>
    <div class="mb-3">
        <label for="categoria" class="form-label">Categoria</label>
        <select id="categoria" name="categoria" class="form-select">
            <option>seleccionar</option>
            @foreach ($categorias as $categoria)
            <option value="{!! $categoria->id !!}">{!! $categoria->categoria !!}</option>
            @endforeach
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Crear</button>
  </form>

@endsection

resources/views/usuarios_editar.blade.php
@extends('app')

@section('titulo','Editar usuarios')

@section('contenido')

<form method="POST" action="{!! route('usuarios.update',$usuario->id) !!}">
    @csrf

    @method('PUT')

    <div class="mb-3">
      <label for="cedula" class="form-label">Cedula</label>
      <input type="number" class="form-control" id="cedula" name="cedula" value="{!! $usuario->cedula !!}">
    </div>
    <div class="mb-3">
        <label for="nombres" class="form-label">Nombres</label>
        <input type="text" class="form-control" id="nombres" name="nombres" value="{!! $usuario->nombres !!}">
    </div>
    <div class="mb-3">
        <label for="apellidos" class="form-label">Apellidos</label>
        <input type="text" class="form-control" id="apellidos" name="apellidos" value="{!! $usuario->apellidos !!}">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email" value="{!! $usuario->email !!}">
    </div>
    <div class="mb-3">
        <label for="pais" class="form-label">Pais</label>
        <select id="pais" name="pais" class="form-select">
            <option>seleccionar</option>
            @foreach ($paises as $key=>$pais)
                @php
                $select= '';
                if($pais == $usuario->pais){
                    $select = 'selected';
                }
                @endphp
                <option {!! $select !!} value="{!! $key !!}">{!! $pais !!}</option>
            @endforeach
        </select>
    </div>
    <div class="mb-3">
        <label for="direccion" class="form-label">Dirección</label>
        <input type="text" class="form-control" id="direccion" name="direccion" value="{!! $usuario->direccion !!}">
    </div>
    <div class="mb-3">
        <label for="celular" class="form-label">Celular</label>
        <input type="number" class="form-control" id="celular" name="celular" value="{!! $usuario->celular !!}">
    </div>
    <div class="mb-3">
        <label for="categoria" class="form-label">Categoria</label>
        <select id="categoria" name="categoria" class="form-select">
            <option>seleccionar</option>
            @foreach ($categorias as $categoria)
                @php
                $select= '';
                if($categoria->id == $usuario->categoria_id){
                    $select = 'selected';
                }
                @endphp
                <option {!! $select !!} value="{!! $categoria->id !!}">{!! $categoria->categoria !!}</option>
            @endforeach
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Editar</button>
  </form>

@endsection